<div style="text-slign:center; margin:0 auto;width:100%;">
    <video id="broadcast" autoplay style="width: 400px; height: 300px; border: outset;"></video>
    <canvas id="canvas" style="display:none;width: 400px; height: 300px; border: outset;" height="300" width="400"></canvas>
    <img id="else" style="width: 400px; height: 300px; border: outset;" height="300" width="400"/>
</div>
<br/>
<div id="status"></div>
<script src="http://<?php echo $_SERVER['HTTP_HOST']?>:1337/socket.io/socket.io.js"></script>
<script>
$(function() {
    if ('undefined' == typeof io) {
        return;
    }
    var socket = io.connect('http://'+window.location.hostname+':1337');
    if ('undefined' == typeof socket) {
        return;
    }
    
    socket.on('message', function (data) {
        console.log(data);
    });
    socket.on('frame', function(data) {
        document.getElementById('else').setAttribute('src', data.src);
    });
});

$(function() {
    navigator.getUserMedia_ = 
        navigator.getUserMedia ||
        navigator.webkitGetUserMedia || 
        navigator.mozGetUserMedia ||
        navigator.msGetUserMedia;
        
    if('undefined' == typeof navigator.getUserMedia_) {
        $('#status').html('getUserMedia is not supported in your browser. This is an experimental feature.');
        return;
    }
    navigator.getUserMedia_({ video: true, audio: false },
        function (stream) {
    	    var domURL = window.URL || window.webkitURL;
        	//start streaming via the video element
        	document.getElementById('broadcast').src =
    	        domURL ? domURL.createObjectURL(stream) : stream;
    	        
    	    var video = document.getElementById('broadcast');
            var canvas = document.getElementById('canvas');
            var ctx = canvas.getContext('2d');

            setInterval(
                function() {
                    ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
                    if ('undefined' != typeof socket) {
                        socket.emit('frame', {"src": canvas.toDataURL('image/png') });
                    }
                },
                100
            );

        },
        function() {
            $('#status').html('Could not run getUserMedia - you probably denied it');
        }
    );
});
</script>
