<div style="text-slign:center; margin:0 auto;width:100%;">
    <video id="broadcast" autoplay style="width: 400px; height: 300px; border: outset;"></video>
    <canvas id="canvas" style="display:none;width: 400px; height: 300px; border: outset;" height="300" width="400"></canvas>
    <img id="else" style="width: 400px; height: 300px; border: outset;" height="300" width="400"/>
</div>
<script src="http://<?php echo $_SERVER['HTTP_HOST']?>:1337/socket.io/socket.io.js"></script>
<script>
$(function() {
    var socket = io.connect('http://'+window.location.hostname+':1337');
    socket.on('message', function (data) {
        console.log(data);
    });

    navigator.getUserMedia_ = navigator.getUserMedia || navigator.webkitGetUserMedia || 
        navigator.mozGetUserMedia || navigator.msGetUserMedia;
    if('undefined' == typeof navigator.getUserMedia_) {
        console.log('No api');
        return;
    }
    navigator.getUserMedia_({ video: true, audio: false },
        function (stream) {
    	    var domURL = window.URL || window.webkitURL;
        	//start streaming via the video element
        	document.getElementById('broadcast').src =
    	        domURL ? domURL.createObjectURL(stream) : stream;
    	        
    	    var video = document.getElementById('broadcast');
            var canvas = document.getElementById('canvas');
            var ctx = canvas.getContext('2d');

            setInterval(
                function() {
                    ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
                    socket.emit('frame', {"src": canvas.toDataURL('image/webp') });
                },
                100
            );

        },
        function() {
            console.log('fail');
        }
    );


    socket.on('frame', function(data) {
        document.getElementById('else').setAttribute('src', data.src);
    });
});
</script>
