<?php
/**
 * This file is part of Project Chaplin.
 *
 * Project Chaplin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Project Chaplin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Project Chaplin. If not, see <http://www.gnu.org/licenses/>.
 *
 * @package    Project Chaplin
 * @author     Dan Dart
 * @copyright  2012-2013 Project Chaplin
 * @license    http://www.gnu.org/licenses/agpl-3.0.html GNU AGPL 3.0
 * @version    git
 * @link       https://github.com/dandart/projectchaplin
**/
?>
<div class="content-header">
    Search for "<?php echo $this->strSearchTerm; ?>"
</div>
<div class="content-centre">
<?php foreach($this->ittVideos as $modelVideo):?>
<div class="video">
	<a href="/video/watch/id/<?php echo $modelVideo->getVideoId();?>">
		<div class="thumb-wrapper">
    		<img class="thumb-img" src="<?php echo htmlentities($modelVideo->getThumbnail());?>" alt="View Video"/>
		</div>
		<p><?php echo $modelVideo->getShortTitle();?></p>
	</a>
</div>
<?php endforeach;?>
</div>
<div class="clearfix"></div>
<br/>

<?php if ($this->ytUser) : ?>
	<h2>Found YouTube user <?php echo $this->strSearchTerm; ?></h2>
	<div class="content-centre">
		<div class="video">
			<a href="/user/youtube/id/<?php echo $this->strSearchTerm; ?>">
				<div class="thumb-wrapper">
	    			<img class="thumb-img" src="<?php echo htmlentities($this->ytUser->getThumbnail()->getUrl());?>" alt="View User"/>
	    		</div>
				<p><?php echo $this->ytUser->getUsername();?></p>
			</a>
		</div>
	</div>
	<div class="clearfix"></div>
<?php endif; ?>
<rr/>
<h2>YouTube results for: <?php echo $this->strSearchTerm; ?></h2>
<div class="content-centre" id="youtubevids">
<?php foreach($this->videoFeed as $ytVideo):?>
<div class="video">
	<a href="/video/watchyoutube/id/<?php echo $ytVideo->getVideoId(); ?>">
		<div class="thumb-wrapper">
<?php
$arrThumbnails = $ytVideo->getVideoThumbnails();
if (isset($arrThumbnails[0])) :?>
    		<img class="thumb-img" src="<?php echo htmlentities($arrThumbnails[0]['url']);?>" alt="View Video"/>
<?php endif;?>
		</div>
		<p><?php echo $ytVideo->getVideoTitle();?></p>
	</a>
</div>
<?php endforeach;?>

</div>
<script src="/js/search.js"></script>