<?php
/**
 * This file is part of Project Chaplin.
 *
 * Project Chaplin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Project Chaplin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Project Chaplin. If not, see <http://www.gnu.org/licenses/>.
 *
 * @package    Project Chaplin
 * @author     Kathie Dart
 * @copyright  2012-2013 Project Chaplin
 * @license    http://www.gnu.org/licenses/agpl-3.0.html GNU AGPL 3.0
 * @version    git
 * @link       https://github.com/kathiedart/projectchaplin
**/
?>
<div class="content-header">
    Search for "<?php echo $this->strSearchTerm; ?>"
</div>
<div class="content-centre">
<?php foreach($this->ittVideos as $modelVideo):?>
<div class="video">
	<a href="/video/watch/id/<?php echo $modelVideo->getVideoId();?>">
		<div class="thumb-wrapper">
    		<img class="thumb-img" src="<?php echo htmlentities($modelVideo->getThumbnail());?>" alt="View Video"/>
		</div>
		<p><?php echo $modelVideo->getShortTitle();?></p>
	</a>
</div>
<?php endforeach;?>
</div>
<div class="clearfix"></div>
<?php if ($this->ytUser) : ?>
	<h2>Found YouTube user <?php echo $this->ytUser->getSnippet()->title; ?></h2>
	<div class="content-centre">
		<div class="video">
			<a href="/user/youtube/id/<?php echo $this->ytUser->id; ?>">
				<div class="thumb-wrapper">
	    			<img class="thumb-img" src="<?php echo $this->ytUser->getSnippet()->thumbnails->high->url;?>" alt="View User"/>
	    		</div>
				<p><?php echo $this->ytUser->getSnippet()->title;?></p>
			</a>
		</div>
	</div>
	<div class="clearfix"></div>
<?php endif; ?>
<?php if ($this->vimeoUser) : ?>
	<h2>Found Vimeo user <?php echo $this->vimeoUser['name']; ?></h2>
	<div class="content-centre">
		<div class="video">
			<a href="/user/vimeo/id/<?php echo substr($this->vimeoUser['uri'], 8); ?>">
				<div class="thumb-wrapper">
	    			<img class="thumb-img" src="" alt="View User"/>
	    		</div>
				<p><?php echo $this->vimeoUser['name'];?></p>
			</a>
		</div>
	</div>
	<div class="clearfix"></div>
<?php endif; ?>
<h2>YouTube results for: <?php echo $this->strSearchTerm; ?></h2>
<div class="content-centre" id="youtubevids">
<?php foreach($this->videoFeed->items as $ytVideo): ?>
<div class="video">
	<a href="/video/watchyoutube/id/<?php echo $ytVideo->getId()->videoId; ?>">
		<div class="thumb-wrapper">
    		<img class="thumb-img" src="<?php echo htmlentities($ytVideo->getSnippet()->getThumbnails()->high->url);?>" alt="View Video"/>
		</div>
		<p><?php echo $ytVideo->getSnippet()->getTitle();?></p>
	</a>
</div>
<?php endforeach;?>
</div>
<div class="clearfix"></div>
<h2>Vimeo results for: <?php echo $this->strSearchTerm; ?></h2>
<div class="content-centre" id="youtubevids">
<?php if (isset($this->vimeoFeed['data'])):
foreach($this->vimeoFeed['data'] as $arrVideo): ?>
<div class="video">
	<a href="/video/watchvimeo/id/<?php echo substr($arrVideo['uri'], 8); ?>">
		<div class="thumb-wrapper">
    		<img class="thumb-img" src="<?php echo htmlentities($arrVideo['pictures']['sizes'][3]['link']);?>" alt="View Video"/>
		</div>
		<p><?php echo $arrVideo['name'];?></p>
	</a>
</div>
<?php endforeach;
endif;?>
</div>
<script src="/js/search.js"></script>
