<?php
	$checksOkay = true;
	function check(&$checksOkay, $x, $errtxt)
	{
		$checksOkay = $checksOkay && $x;
		return ($x)?'<span class="ok">OK</span>':'<span class="error">Not OK: '.$errtxt.'</span>';
	}

	function pdo_supports($type)
	{
		return in_array($type, PDO::getAvailableDrivers());
	}

	$check1 = check($checksOkay, 50500 <= PHP_VERSION_ID, 'version '.PHP_VERSION);
	$check2 = check($checksOkay, class_exists('PDO'), 'PDO not installed');
	$check3 = check($checksOkay, 0 < count(PDO::getAvailableDrivers()), 'No drivers available');
	$check4 = check($checksOkay, class_exists('AMQPConnection'), 'AMQP not found');
	$check5 = check($checksOkay, "0" == exec('ffmpeg -version 2>&1; echo $?'), 'Failed: ffmpeg not found');
	$check6 = check($checksOkay, "0" == exec('npm --version 2>&1; echo $?'), 'Failed: npm not found');
?>
<div class="widgetbox medium centre">
	<div class="widgettitle">
		Welcome!
	</div>
	<div id="step0" class="widgetbody" style="text-align:left; padding:30px">
		<p>Welcome to Project Chaplin!</p>
		<p>Thank you for choosing the newest addition to Internet video sharing.</p>
		<p>Project Chaplin features:
		<ul>
			<li>A free software, open source licence as standard</li>
			<li>No intrusive adverts</li>
			<li>Import videos from popular video sources</li>
			<li>No restrictions on content by country, IP or government</li>
			<li>Video downloading as standard</li>
			<li>HTML5 WebM as standard</li>
			<li>Live streaming (pluginless)</li>
			<li>Federation through multiple servers</li>
			<li>Live video effects including brightness and contrast</li>
			<li>Easter eggs<a href="#" onclick='$(document).addClass("br");'>?</a></li>
		</ul>
		<p>In the pipeline are:
		<ul>
			<li>REST APIs</li>
			<li>Blocking on public demand</li>
			<li>Federated APIs</li>
			<li>Public tagging of videos</li>
			<li>Channel subscriptions</li>
			<li>Individual profiles</li>
			<li>Audio downloading</li>
			<li><a href="https://github.com/dandart/projectchaplin/issues">See All</a></li>
		</ul>
		<p>Let's set up your install. It only takes a couple of minutes to get going.</p>
		<p class="centre"><a href="#step1" class="switcher btn btn-success">Okay, let's go!</a></p>
	</div>
	<div id="step1" class="widgetbody" style="display:none;text-align:left; padding:30px">
		<h2>Awesome!</h2>
		<p>Let's check your plugins and extensions first.</p>
		<p><strong>PHP >= 5.5</strong>: <?php echo $check1 ?></p>
		<p><strong>PDO</strong>: <?php echo $check2 ?></p>
		<p><strong>A PDO database extension is installed</strong>: <?php echo $check3 ?></p>
		<p><strong>AMQP extension (for encoding and importing batch jobs)</strong>: <?php echo $check4 ?></p>
		<p><strong>Compatible encoder present</strong>: <?php echo $check5 ?></p>
		<p><strong>Node.js and npm</strong>: <?php echo $check6 ?></p>
		<p></p>
		<?php if ($checksOkay):?>
			<p class="centre"><a href="#step2" class="switcher btn btn-success">Great! Let's continue!</a></p>
		<?php else : ?>
			<p class="centre warning">Sorry, not all of the dependencies are met. Please install the required packages.</p>
		<?php endif;?>
	</div>
	<div id="step2" class="widgetbody" style="display:none;text-align:left; padding:30px">
		<h2>Great!</h2>
		<p>Let's set up your database. Please enter the details for your database server.</p>
		<form id="sqlserver">
			<p>
				<label for="selSQLType">SQL Server Type (to add more, add to packages)</label>
				<select id="selSQLType" name="adapter">
				<?php if (pdo_supports('ibm')): ?>
					<option value="Pdo_Ibm">IBM DB2</option>
				<?php endif;
				if (pdo_supports('sqlsrv')): ?>
					<option value="Pdo_Mssql">MSSQL</option>
				<?php endif;
				if (pdo_supports('mysql')): ?>
					<option value="Pdo_Mysql">MySQL / MariaDB</option>
				<?php endif;
				if (pdo_supports('oci')): ?>
					<option value="Pdo_Oci">Oracle</option>
				<?php endif;
				if (pdo_supports('pgsql')): ?>
					<option value="Pdo_Pgsql">PostgreSQL</option>
				<?php endif;
				if (pdo_supports('sqlite')): ?>
					<option value="Pdo_Sqlite">SQLite</option>
				<?php endif; ?>
				</select>
			</p>
			<p>
				<label for="strHost">Host: </label>
				<input type="text" id="strHost" name="params[host]" value="localhost"/>
			</p>
			<p>
				<label for="strUsername">Username (if applicable): </label>
				<input type="text" id="strUsername" name="params[username]" placeholder="Username here"/>
			</p>
			<p>
				<label for="strPassword">Password (if applicable): </label>
				<input type="password" id="strPassword" name="params[password]" placeholder="Password here"/>
			</p>
			<p>
				<label for="strDatabase">Database (if applicable): </label>
				<input type="text" id="strDatabase" name="params[dbname]" placeholder="Database Name"/>
			</p>
			<p>
				<label for="strSchema">Schema (if applicable): </label>
				<input type="text" id="strSchema" name="params[schema]" placeholder="Schema Name"/>
			</p>
			<!-- TODO: Table Prefix -->
		</form>
		<a href="#"
			data-output-element="testresult"
			data-url="/admin/setup/sqltest"
			data-form="sqlserver"
			class="ajax btn btn-default">I want to test this</a>
		<span id="testresult"></span>
		<a href="#step1" class="switcher btn btn-default"><i class="fa fa-arrow-left"></i> Go back</a>
		<a href="#step3" class="switcher btn btn-success">Okay! Go ahead!</a>
	</div>
	<div id="step3" class="widgetbody" style="display:none;text-align:left; padding:30px">
		<h2>Amazing!</h2>
		<p>Let's set up your AMQP server.</p>
		<form id="amqp">
			<p>
				<label for="strHost">Host: </label>
				<input type="text" id="strHost" name="host" value="localhost"/>
			</p>
			<p>
				<label for="strPort">Port: </label>
				<input type="text" id="strPort" name="port" value="5672"/>
			</p>
			<p>
				<label for="strUsername">Username: </label>
				<input type="text" id="strUsername" name="username" value="guest" placeholder="Username here"/>
			</p>
			<p>
				<label for="strPassword">Password: </label>
				<input type="password" id="strPassword" name="password" value="guest" placeholder="Password here"/>
			</p>
		</form>
		<a href="#"
			data-output-element="amqpresult"
			data-url="/admin/setup/amqptest"
			data-form="amqp"
			class="ajax btn btn-default">I want to test this</a>
		<span id="amqpresult"></span>
		<a href="#step2" class="switcher btn btn-default"><i class="fa fa-arrow-left"></i> Go back</a>
		<a href="#step4" class="switcher btn btn-success">Great! Next bit!</a>
	</div>
	<div id="step4" class="widgetbody" style="display:none;text-align:left; padding:30px">
		<h2>Just a couple of steps to go</h2>
		<p>Please provide details of your mail server for notifications. Usually the defaults will suffice.</p>
		<form id="smtp">
			<p>
				<label for="strHost">Host: </label>
				<input type="text" id="strHost" name="host" value="localhost"/>
			</p>
			<p>
				<label for="strPort">Port: </label>
				<input type="text" id="strPort" name="options[port]" value="25"/>
			</p>
			<p>
				<label for="strUsername">Username: </label>
				<input type="text" id="strUsername" name="options[username]" value="" placeholder="Username here"/>
			</p>
			<p>
				<label for="strPassword">Password: </label>
				<input type="password" id="strPassword" name="options[password]" value="" placeholder="Password here"/>
			</p>
			<p>
				<input type="hidden" name="options[auth]" value="login"/>
				SSL?
				<br/>
				<label for="rdSSLYes">
					<input type="radio" id="rdSSLYes" name="options[ssl]" value="tls"/> Yes
				</label>
				<br/>
				<label for="rdSSLNo">
					<input type="radio" id="rdSSLNo" name="options[ssl]" value=""/> No
				</label>
			</p>
		</form>
		<a href="#step3" class="switcher btn btn-default"><i class="fa fa-arrow-left"></i> Go back</a>
		<a href="#step5" class="switcher btn btn-success">Great! Go on to the last step!</a>
	</div>
	<div id="step5" class="widgetbody" style="display:none;text-align:left; padding:30px">
		<h2>What is your website address?</h2>
		<form id="vhost">
			<p>
				<label for="vhAddress">Address: </label>
				<input type="text" id="vhAddress" name="vhost" value="<?php echo $_SERVER['HTTP_HOST'] ?>" placeholder="URL here"/>
			</p>
			<p>
				HTTPS?
				<br/>
				<label for="vhSSLYes">
					<input type="radio" id="vhSSLYes" name="ssl" value="true"/> Yes
				</label>
				<br/>
				<label for="vhSSLNo">
					<input type="radio" id="vhSSLNo" name="ssl" value="false"/> No
				</label>
			</p>
			<p>
				<label for="strShort">Short URL: </label>
				<input type="text" id="strShort" name="short" value="" placeholder="Short URL"/>
			</p>
		</form>
		<a href="#step6" class="switcher ajax btn btn-success commit">Awesome! Let's write it!</a>
	</div>
	<div id="step6" class="widgetbody" style="display:none;text-align:left; padding:30px">
		<h2>Your Settings</h2>
		<textarea id="commitresult" cols="55" rows="10">Output will appear here</textarea>
        <p><a href="#" class="commit btn btn-default">Retry</a></p>
		<p><a href='/' class="btn btn-success">I'm ready, start using Chaplin</a></p>
	</div>
</div>
<script>
    $.fn.serializeObject = function(){
        var self = this,
            json = {},
            push_counters = {},
            patterns = {
                "validate": /^[a-zA-Z][a-zA-Z0-9_]*(?:\[(?:\d*|[a-zA-Z0-9_]+)\])*$/,
                "key":      /[a-zA-Z0-9_]+|(?=\[\])/g,
                "push":     /^$/,
                "fixed":    /^\d+$/,
                "named":    /^[a-zA-Z0-9_]+$/
            };


        this.build = function(base, key, value){
            base[key] = value;
            return base;
        };

        this.push_counter = function(key){
            if(push_counters[key] === undefined){
                push_counters[key] = 0;
            }
            return push_counters[key]++;
        };

        $.each($(this).serializeArray(), function(){

            // skip invalid keys
            if(!patterns.validate.test(this.name)){
                return;
            }

            var k,
                keys = this.name.match(patterns.key),
                merge = this.value,
                reverse_key = this.name;

            while((k = keys.pop()) !== undefined){

                // adjust reverse_key
                reverse_key = reverse_key.replace(new RegExp("\\[" + k + "\\]$"), '');

                // push
                if(k.match(patterns.push)){
                    merge = self.build([], self.push_counter(reverse_key), merge);
                }

                // fixed
                else if(k.match(patterns.fixed)){
                    merge = self.build([], k, merge);
                }

                // named
                else if(k.match(patterns.named)){
                    merge = self.build({}, k, merge);
                }
            }

            json = $.extend(true, json, merge);
        });

        return json;
    };

	$('a.switcher').click(function() {
		var self = this;
		$('.widgetbody').hide();
		$($(self).attr('href')).show();
	});
	$('a.ajax').click(function() {
		var self = this;
		$.post(
			$(self).attr('data-url'),
			$('#'+$(self).attr('data-form')).serialize(),
			function(data) {
				$('#'+$(self).attr('data-output-element')).html(data);
			}
		);
	})
	$('.commit').click(function() {
		vhost = $('#vhost').serializeObject();

		$.post('/admin/setup/write',
		{
			locale: 'en_GB',
			amqp: {
				servers: {
					read: $('#amqp').serializeObject(),
					write: $('#amqp').serializeObject()
				}
			},
			smtp: {
				server: $('#smtp').serializeObject()
			},
			dbtype: 'sql',
			sql: $('#sqlserver').serializeObject(),
			vhost: vhost.vhost,
			ssl: vhost.ssl,
			short: vhost.short
		}, function(data)
		{
			$('#commitresult').text(data);
		});
	});
</script>
