<?php
/**
 * This file is part of Project Chaplin.
 *
 * Project Chaplin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Project Chaplin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Project Chaplin. If not, see <http://www.gnu.org/licenses/>.
 *
 * @package    Project Chaplin
 * @author     Dan Dart
 * @copyright  2012-2013 Project Chaplin
 * @license    http://www.gnu.org/licenses/agpl-3.0.html GNU AGPL 3.0
 * @version    git
 * @link       https://github.com/dandart/projectchaplin
**/
?>
<div class="content-header">
    Videos for user <?php echo $this->strUsername; ?>
</div>
<div class="content-centre">
<?php foreach($this->ittVideos as $videoEntry):?>
<a href="/video/watchyoutube/id/<?php echo $videoEntry->getVideoId();?>">
<div class="thumb-wrapper">
<div class="thumb-img">
    <img src="<?php
    	$thumbnails = $videoEntry->getVideoThumbnails();
    	echo htmlentities(
    		(
    			isset($thumbnails[0]) &&
	    	 	isset($thumbnails[0]['url'])
    		)?
    		$thumbnails[0]['url']:
    		null
    	);?>" alt="View Video"/>
</div>
<p><?php echo $videoEntry->getTitle();?></p>
</div>
</a>
<?php endforeach;?>
</div>
<div style="clear:both"></div>
<br/>
<?php if ($this->bHasUserFavourites) : ?>
<div class="content-header">
	    Favourites for user <?php echo $this->strUsername; ?>
	</div>
	<div class="content-centre">
	<?php foreach($this->ittFavourites as $videoEntry):?>
	<a href="/video/watchyoutube/id/<?php echo $videoEntry->getVideoId();?>">
	<div class="thumb-wrapper">
	<div class="thumb-img">
	    <img src="<?php
    	$thumbnails = $videoEntry->getVideoThumbnails();
    	echo htmlentities(
    		(
    			isset($thumbnails[0]) &&
	    	 	isset($thumbnails[0]['url'])
    		)?
    		$thumbnails[0]['url']:
    		null
    	);?>" alt="View Video"/>
	</div>
	<p><?php echo $videoEntry->getTitle();?></p>
	</div>
	</a>
	<?php endforeach;?>
	</div>
<?php endif; ?>