<div class="fb-share-button"
    data-href="'.$url.'"
    data-layout="button_count"
    data-size="small"
    data-mobile-iframe="false"
>
    <a class="fb-xfbml-parse-ignore"
        target="_blank"
        href="https://www.facebook.com/sharer/sharer.php?u='.
            <?php echo urlencode(
                $this->vhost.
                '/video/watch/id/'.
                $this->video->getVideoId()
            );?>&amp;src=sdkpreparse">
            Share
    </a>
</div>
