<!-- Facebook Meta Tags -->
<meta property="og:url"           content="<?php echo $this->url; ?>" />
<meta property="og:type"          content="website" />
<meta property="og:title"         content="<?php echo $this->title; ?>" />
<meta property="og:description"   content="<?php echo $this->description; ?>" />
<meta property="og:image"         content="<?php echo $this->image; ?>" />
<!-- Load Facebook SDK for JavaScript -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.7&appId=<? echo $this->facebookAppId ?>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<!-- End Facebook Meta Tags -->
