<?php
/**
 * This file is part of Project Chaplin.
 *
 * Project Chaplin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Project Chaplin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Project Chaplin. If not, see <http://www.gnu.org/licenses/>.
 *
 * @package    Project Chaplin
 * @author     Dan Dart
 * @copyright  2012-2013 Project Chaplin
 * @license    http://www.gnu.org/licenses/agpl-3.0.html GNU AGPL 3.0
 * @version    git
 * @link       https://github.com/dandart/projectchaplin
**/
?>
<!-- Please feel free to change or remove this button on your own server. :-) -->
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="BYUBE8F5P4FZE">
<p>
Copyright &copy; Project Chaplin. Videos copyright &copy; respective authors. &nbsp;
<a href="https://github.com/dandart/projectchaplin">Source</a> &nbsp;
<a href="/COPYING">Licence</a> &nbsp;
<a href="https://github.com/dandart/projectchaplin/issues?state=open">Issues</a> &nbsp;
<a href="mailto:chaplin@dandart.co.uk">Contact</a> &nbsp;
Servers cost money, please help out.
<!-- In fact, Chaplin costs me around £15 per month to maintain, which I cannot afford every month. So, thank you. -->
<input type="image" src="https://www.paypalobjects.com/en_GB/i/btn/btn_donate_SM.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online.">
<img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
</p>
</form>
