<div class="left">
    <a href="/">Home</a> |
    <a href="/video/upload">Upload</a> |
    <a href="/broadcast">Broadcast</a>
</div>
<div class="middle">
	Project Chaplin Video Sharing
</div>
<div class="right">
    <?php if(Chaplin_Auth::getInstance()->hasIdentity()) :
        $modelUser = Chaplin_Auth::getInstance()->getIdentity()->getUser(); ?>
        Logged in as <strong><?php echo $modelUser->getUsername(); ?> - <?php echo $modelUser->getUserType()->getUserType();?></strong> | <a href="/userinfo">User Info</a> | <a href="/logout">Logout</a>
    <?php else: ?>
        <a href="/login">Login</a>
    <?php endif; ?>
</div>
