<?php
/**
 * This file is part of Project Chaplin.
 *
 * Project Chaplin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Project Chaplin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Project Chaplin. If not, see <http://www.gnu.org/licenses/>.
 *
 * @package    Project Chaplin
 * @author     Dan Dart
 * @copyright  2012-2013 Project Chaplin
 * @license    http://www.gnu.org/licenses/agpl-3.0.html GNU AGPL 3.0
 * @version    git
 * @link       https://github.com/dandart/projectchaplin
**/
$bIsLoggedIn = false;
if(Chaplin_Auth::getInstance()->hasIdentity()) :
    $modelUser = Chaplin_Auth::getInstance()->getIdentity()->getUser();
    $bIsLoggedIn = true;
endif;
?>
<div class="left">
    <a href="/">Home</a> |
    <a href="/video/upload">Upload</a> |
    <a href="/broadcast">Broadcast</a>
    <?php if ($bIsLoggedIn && $modelUser->isGod()) :?>
    | <a href="/admin/import">Import</a>
    | <a href="/admin/user">Users</a>
    | <a href="/admin/node">Nodes</a>
    <?php endif; ?>
</div>
<div class="middle">
	Project Chaplin Video Sharing
</div>
<div class="right">
    <?php if($bIsLoggedIn): ?>
        Logged in as <strong>
            <a href="/user/<?php echo $modelUser->getUsername();?>">
                <?php echo $modelUser->getNick(); ?>
            </a> - 
            <?php echo $modelUser->getUserType()->getUserType();?>
        </strong> |
        <a href="/userinfo">User Info</a> |
        <a href="/messages"><?php echo $modelUser->getMessages()->count(); ?>
        <a href="/logout">Logout</a>
    <?php else: ?>
        <a href="/login">Login</a>
    <?php endif; ?>
    <br/><br/><?php //ZF this shiz ?>
    <form action="/search" method="get">
        <input type="text" id="search" placeholder="Search for videos..." name="search"/>
    </form>
</div>
<div style="clear:both;"></div>
<br/>
