<!DOCTYPE html>
<html>
<head>
    <title>Chaplin</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" type="text/css" href="/css/chaplin.css"/>
    <script type="text/javascript" src="/js/jquery-1.5.min.js"></script>
    <script type="text/javascript" src="/js/jquery.color.js"></script>
    <script type="text/javascript" src="/js/script.js"></script>
</head>
<body>
    <div id="contentwrapper">
        <header>
            <?php echo $this->render('_header.phtml'); ?>
        </header>
        <div id="content">
            <?php echo $this->layout()->content; ?>
        </div>
        </div>
        <footer>
            <?php echo $this->render('_footer.phtml'); ?>
        </footer>
    </div>
</body>
</html>
