<!DOCTYPE html>
<html>
<head>
<title><?php echo APP_NAME; ?></title>
    <link rel="stylesheet" type="text/css" href="/css/style.css"/>
    <script type="text/javascript" src="/js/jquery-1.5.min.js"></script>
    <script type="text/javascript" src="/js/jquery.color.js"></script>
    <script type="text/javascript" src="/js/script.js"></script>
</head>
<body>
    <div id="contentwrapper">
        <div id="appspace">
            <header>
                <?php echo $this->render('_header.phtml'); ?>
            </header>
            <div id="appcontent">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
        <nav id="launcher">
            <?php echo $this->render('_launcher.phtml'); ?>
        </nav>
    </div>
</body>
</html>
