<?php
/**
 * This file is part of Project Chaplin.
 *
 * Project Chaplin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Project Chaplin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Project Chaplin. If not, see <http://www.gnu.org/licenses/>.
 *
 * @package    Project Chaplin
 * @author     Kathie Dart
 * @copyright  2012-2013 Project Chaplin
 * @license    http://www.gnu.org/licenses/agpl-3.0.html GNU AGPL 3.0
 * @version    git
 * @link       https://github.com/kathiedart/projectchaplin
**/
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <title><?php if (isset($this->strTitle)): echo $this->strTitle . ' - '; endif;?>Chaplin</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="apple-mobile-web-app-capable" content="yes" />
</head>
<body>
    <div id="contentwrapper">
        <header>
            <?php echo $this->render('_headerplain.phtml'); ?>
        </header>
        <div style="clear:both"></div>
        <main>
            <?php echo $this->layout()->content; ?>
            <div class="footerpush"></div>
        </main>
        <footer>
            <?php echo $this->render('_footer.phtml'); ?>
        </footer>
    </div>
    <script src="/js/index.js"></script>
</body>
</html>
