<?php
/**
 * This file is part of Project Chaplin.
 *
 * Project Chaplin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Project Chaplin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Project Chaplin. If not, see <http://www.gnu.org/licenses/>.
 *
 * @package    Project Chaplin
 * @author     Dan Dart
 * @copyright  2012-2013 Project Chaplin
 * @license    http://www.gnu.org/licenses/agpl-3.0.html GNU AGPL 3.0
 * @version    git
 * @link       https://github.com/danwdart/projectchaplin
**/
$strNick = $this->modelUser->getNick();
$bIsMe = $this->modelUser
?>

<h3 class="profiletitle">
	<div class="face"></div>
	<?php echo $strNick;?>'s profile
</h3>

<div class="widgetbox text-center col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-sm-12 col-xs-12">

<div class="p-3">
    <?php echo $strNick;?> lives here.
</div>

<?php if ($this->bIsMe) : ?>
	<div class="widgettitle text-center p-3">
	    Update your details
	</div>
	<div class="widgetbody text-center p-3">
	    <?php echo $this->form; ?>
	</div>
</div>

<?php else : ?>

</div>

<?php endif; ?>
