<?php
/**
 * This file is part of Project Chaplin.
 *
 * Project Chaplin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Project Chaplin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Project Chaplin. If not, see <http://www.gnu.org/licenses/>.
 *
 * @package    Project Chaplin
 * @author     Dan Dart
 * @copyright  2012-2013 Project Chaplin
 * @license    http://www.gnu.org/licenses/agpl-3.0.html GNU AGPL 3.0
 * @version    git
 * @link       https://github.com/danwdart/projectchaplin
**/
?>
<h1>
    <?php if (isset($this->ittVideos->items[0])): ?>
    Videos for user <?php echo $this->ittVideos->items[0]->getSnippet()->channelTitle; ?>
    <?php else: ?>
    Videos
    <?php endif; ?>
</h1>
<div class="row text-center">
<?php foreach($this->ittVideos->items as $videoEntry):?>
    <a href="/video/watchyoutube/id/<?php echo $videoEntry->id->videoId;?>" data-next-page-token="<?php echo $this->ittVideos->nextPageToken; ?>">
        <div class="thumb col-lg-4 col-md-4 col-sm-6 col-xs-12">
            <img src="<?php echo htmlentities($videoEntry->getSnippet()->thumbnails->high->url);?>" alt="View Video"/>
            <p><?php echo $videoEntry->getSnippet()->title;?></p>
        </div>
    </a>
<?php endforeach;?>
</div>
