<?php
/**
 * This file is part of Project Chaplin.
 *
 * Project Chaplin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Project Chaplin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Project Chaplin. If not, see <http://www.gnu.org/licenses/>.
 *
 * @package    Project Chaplin
 * @author     Dan Dart
 * @copyright  2012-2013 Project Chaplin
 * @license    http://www.gnu.org/licenses/agpl-3.0.html GNU AGPL 3.0
 * @version    git
 * @link       https://github.com/danwdart/projectchaplin
**/
?>
<h1><?php echo $this->message ?></h1>
<?php if (isset($this->exception)): ?>
<?php if ('development' == APPLICATION_ENV): ?>
<h2><?php echo $this->exception->getMessage() ?></h2>
	<h3>Exception Class: </h3>
	<pre>
<?php echo get_class($this->exception); ?>
	</pre>
    <h3>Backtrace:</h3>
    <pre>
<?php echo $this->exception->getTraceAsString() ?>
    </pre>
    <h3>Request Parameters:</h3>
    <pre>
<?php echo var_export($this->_request->getParams(), true)?>
    </pre>
<?php endif; endif;?>