<?php
/**
 * This file is part of Project Chaplin.
 *
 * Project Chaplin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Project Chaplin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Project Chaplin. If not, see <http://www.gnu.org/licenses/>.
 *
 * @package    Project Chaplin
 * @author     Dan Dart
 * @copyright  2012-2013 Project Chaplin
 * @license    http://www.gnu.org/licenses/agpl-3.0.html GNU AGPL 3.0
 * @version    git
 * @link       https://github.com/danwdart/projectchaplin
**/
?>
<link rel="alternate" type="application/json+oembed"
  href="<?php echo $this->vhost ?>/services/oembed?url=<?php echo $this->vhost ?>/video/watch/id/<?php echo $this->video->getVideoId() ?>&format=json"
  title="<?php echo $this->video->getTitle() ?>" />
<link rel="alternate" type="application/xml+oembed"
  href="<?php echo $this->vhost ?>/services/oembed?url=<?php echo $this->vhost ?>/video/watch/id/<?php echo $this->video->getVideoId() ?>&format=xml"
  title="<?php echo $this->video->getTitle() ?>" />

<?php echo $this->partial("partials/fbsdk.phtml", [
    "url" => $this->vhost ."/video/watch/id/". $this->video->getVideoId(),
    "title" => $this->video->getTitle()." on Chaplin",
    "description" => urlencode($this->video->getDescription()),
    "image" => $this->vhost . $this->video->getFilename() . ".png",
    "facebookAppId" => $this->facebookAppId
]); ?>
<h1><?php echo $this->video->getTitle();?></h1>
<div class="row text-center" id="videoarea">
	<video class="col-lg-12" id="video" controls poster="<?php echo $this->video->getFilename().'.png?'.time();?>">
        <source src="<?php echo $this->video->getFilename().'?'.time();?>"/>
	</video>
    <div class="btn-group btn-block">
        <button class="ml-0 col-2 infinite btn btn-secondary"><i class="fa fa-refresh"></i> Loop</button>
        <button class="ml-0 col-2 btn btn-secondary" id="slower">&laquo; Slow</button>
        <button class="ml-0 col-2 btn btn-secondary" id="normalspeed">Normal</button>
        <button class="ml-0 col-2 btn btn-secondary" id="faster">Fast &raquo;</button>
        <select class="ml-0 col-4 btn btn-secondary effect">
            <option class="filter" value="none">-- Select Effect --</option>
            <option class="filter" value="blur">Blur</option>
            <option class="filter" value="gray">Grey</option>
            <option class="filter" value="sepia">Sepia</option>
            <option class="filter" value="bright">Bright</option>
            <option class="filter" value="highcontrast">Contrast</option>
            <option class="filter" value="colour">Colourful</option>
            <option class="filter" value="invert">Invert</option>
            <option class="filter" value="saturate">Saturate</option>
            <option class="filter" value="earthquake">Earthquake!</option>
            <option class="filter" value="br">Barrel Roll!</option>
            <option class="filter" value="drunk">Drunk!</option>
        </select>
    </div>
</div>
<div id="infoarea">
    <?php if ($this->video->isMine()): ?>
        <br/>
        <a class="btn btn-info" href="/video/edit/id/<?php echo $this->video->getVideoId();?>"><i class="fa fa-edit"></i> Edit</a>
	    <a class="btn btn-danger" href="/video/delete/id/<?php echo $this->video->getVideoId();?>"><i class="fa fa-times-circle"></i> Delete</a>
        <br/>
	<?php endif; ?>
	<br/>Uploaded by: <a href="/user/<?php echo $this->video->getUsername(); ?>"><?php echo $this->video->getUsername(); ?></a>
	<br/>Uploaded on <?php echo date('d/m/Y H:i', $this->video->getTimeCreated());?> (<?php echo $this->video->getTimeAgo(); ?>)
    <?php if ($this->video->getSource()): ?>
    <br/>Original source: <a href="https://youtube.com/watch?v=<?php echo $this->video->getSource(); ?>" target="_blank">Source Video</a>
    <?php endif; ?>
    <?php if ($this->video->getUploader()): ?>
    <br/>Original author: <?php echo $this->video->getUploader(); ?>
    <?php endif; ?>
    <br/>Licence: <a href="<?php echo $this->video->getLicence()->getURL(); ?>"><?php echo $this->video->getLicence()->getText(); ?></a>
	<br/><?php echo $this->video->getDescription(); ?>
	<p>Short URL: <input type="text" disabled value="<?php echo $this->short; ?>"/></p>
	<p><strong>&uparrow; <?php echo $this->video->getVotesUp(); ?> / <?php echo $this->video->getVotesDown(); ?> &downarrow;</strong></p>
    <?php if ($this->video->getPrivacy()->isPublic()): ?>
        <div class="row bg-light">
            <div class="col-lg-2 col-md-2 col-sm-4 col-12">
                <?php echo $this->partial("partials/twittershare.phtml"); ?>
            </div>
            <div class="col-lg-2 col-md-2 col-sm-4 col-12">
                <?php echo $this->partial("partials/facebookshare.phtml", [
                    'vhost' => $this->vhost,
                    'video' => $this->video
                ]); ?>
            </div>
            <div class="col-lg-2 col-md-2 col-sm-4 col-12">
                <?php echo $this->partial("partials/gplusshare.phtml"); ?>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-4 col-12">
                <?php echo $this->partial("partials/gnusocialshare.phtml"); ?>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-4 col-12">
                <?php echo $this->partial("partials/diasporashare.phtml"); ?>
            </div>
        </div>
    <?php endif; ?>
	<br/>
	<a class="btn btn-primary" href="/video/download/id/<?php echo $this->video->getVideoId();?>"><i class="fa fa-download"></i> Download</a>
    <br/><br/>
    <div class="btn-group">
    	<?php if(\Chaplin\Auth::getInstance()->hasIdentity()): ?>
           <a class="atotext btn btn-secondary<?php echo (1 === $this->video->getYourVote()) ? " active" : ""; ?>" href="/video/vote/id/<?php echo $this->video->getVideoId();?>/vote/up">
               <i class="fa fa-arrow-up"></i>
           </a>
           <a class="atotext btn btn-secondary<?php echo (0 === $this->video->getYourVote()) ? " active" : ""; ?>" href="/video/vote/id/<?php echo $this->video->getVideoId();?>/vote/down">
               <i class="fa fa-arrow-down"></i>
           </a>
    	<?php endif; ?>
    </div>
	<br/><br/>
	<?php if(\Chaplin\Auth::getInstance()->hasIdentity()): echo $this->formComment; else: echo 'Login above to comment.'; endif; ?>
	<br/>
	<div id="comments" rel="/video/comments/id/<?php echo $this->video->getVideoId();?>">
		<?php foreach($this->ittComments as $modelComment):?>
		<p>
			<i>
				<?php echo $modelComment->getUsername();?>
			</i> said:
			<?php echo $modelComment->getComment();?>
			<?php if ($modelComment->isMine()): ?>
				<a class="ajax" href="/video/deletecomment/id/<?php echo $modelComment->getCommentId(); ?>"
					rel="comments">
				(X)
				</a>
			<?php endif;?>
		</p>
	<?php endforeach; ?>
	</div>
</div>
