<?php
/**
 * This file is part of Project Chaplin.
 *
 * Project Chaplin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Project Chaplin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Project Chaplin. If not, see <http://www.gnu.org/licenses/>.
 *
 * @package    Project Chaplin
 * @author     Dan Dart
 * @copyright  2012-2013 Project Chaplin
 * @license    http://www.gnu.org/licenses/agpl-3.0.html GNU AGPL 3.0
 * @version    git
 * @link       https://github.com/danwdart/projectchaplin
**/
?>
<h1><?php echo $this->entryVideo->getSnippet()->title;?></h1>
<div id="videoarea">
	<iframe
        id="video"
		class="youtube-player"
		type="text/html"
		width="720"
		height="405"
		src="https://www.youtube-nocookie.com/embed/<?php echo $this->entryVideo->id; ?>"
		frameborder="0"
        allowfullscreen
	>
	</iframe>
</div>
<div id="infoarea">
	<h3>Uploaded on <?php echo date('d/m/Y H:i', strtotime($this->entryVideo->getSnippet()->publishedAt));
		$author = $this->entryVideo->getSnippet()->channelTitle;
		$strUserUri = $this->entryVideo->getSnippet()->channelId;
        $strChannelId = $this->entryVideo->getSnippet()->channelId;
		$strName =  $this->entryVideo->getSnippet()->channelTitle;
	?> by <a href="/user/youtube/id/<?php echo $strChannelId; ?>"><?php echo $strName; ?></a>
	</h3>
	<br/>
	<span class="text-sm"><?php echo str_replace(
        "\n", '<br/>', (new Misd\Linkify\Linkify())->process(
            $this->entryVideo->getSnippet()->description
        )
    ); ?></span>
	<br/>
	<a class="btn btn-success" href="/video/importyoutube/id/<?php echo $this->entryVideo->id;?>"><i class="fa fa-download"></i> Import</a>
	<?php if ($this->isLocal) : ?>
	<a class="btn btn-primary" href="<?php echo $this->videoURL;?>"><i class="fa fa-download"></i> Download</a>
	<?php endif; ?>
	<br/>
	<?php if(Chaplin_Auth::getInstance()->hasIdentity()): echo $this->formComment; else:
	echo 'Login above to comment.'; endif;  ?>
</div>
