<?php
/**
 * This file is part of Project Chaplin.
 *
 * Project Chaplin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Project Chaplin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Project Chaplin. If not, see <http://www.gnu.org/licenses/>.
 *
 * @package    Project Chaplin
 * @author     Dan Dart
 * @copyright  2012-2013 Project Chaplin
 * @license    http://www.gnu.org/licenses/agpl-3.0.html GNU AGPL 3.0
 * @version    git
 * @link       https://github.com/danwdart/projectchaplin
**/
$bIsLoggedIn = false;
if(Chaplin_Auth::getInstance()->hasIdentity()) :
	$modelUser = Chaplin_Auth::getInstance()->getIdentity()->getUser();
	$bIsLoggedIn = true;
endif;
$bNoUploads = ("true" === getenv("NO_UPLOADS"));
?>

<div class="wrap">
	<a href="/"><div class="logo">
		Chaplin
	</div></a>
	<div class="right">
        <?php if (!$bNoUploads): ?>
		<a href="/video/upload" class="upload button"><i class="fa fa-upload"></i> <span class="hidden-xs">Upload</span></a>
        <?php endif; ?>
		<!--<a href="/broadcast" class="broadcast button"><i class="fa fa-video-camera"></i> Broadcast</a>-->

		<span class="dropdown">
			<a href="#" class="btn btn-transparent dropdown-toggle" data-toggle="dropdown">
				<?php if($bIsLoggedIn): ?>
					<span class="username">
						<?php echo $modelUser->getNick(); ?>
					</span>
					<?php //echo $modelUser->getUserType()->getUserType();?>
				<?php else: ?>
					<span class="username nobold">
						Not logged in
					</span>
				<?php endif; ?>
				<span class="caret"></span></a>
    			<ul class="dropdown-menu pull-right" role="menu">

				<?php if($bIsLoggedIn): ?>
					<li>
						<a href="/user/<?php echo $modelUser->getUsername();?>"><i class="fa fa-user"></i> Profile</a>
					</li>
					<li>
						<a href="/logout"><i class="fa fa-sign-out"></i> Logout</a>
					</li>
				<?php else: ?>
					<li>
						<a href="/login"><i class="fa fa-sign-in"></i> Login</a>
					</li>
				<?php endif; ?>

				<?php /*/if ($bIsLoggedIn && $modelUser->isGod()) :?>
					<li class="divider"></li>
					<li>
						<a href="/admin/import"><i class="fa fa-download"></i> Import</a>
					</li>
					<li>
						<a href="/admin/user"><i class="fa fa-user"></i> Users</a>
					</li>
					<li>
						<a href="/admin/node"><i class="fa fa-sitemap"></i> Nodes</a>
					</li>
					<li>
						<a href="/admin/events"><i class="fa fa-rss"></i> Events</a>
					</li>
				<?php //endif; */ ?>
			</ul>

		</span>
	</div>
	<form class="hidden-xs search" action="/search" method="get">
		<input type="search" id="search" required placeholder="Search for videos..."
		<?php if (isset($this->strSearchTerm)) : echo 'value="'.$this->strSearchTerm.'"'; endif; ?> name="search"/>
		<button type="submit"></button>
	</form>
    <form class="visible-xs search">S</forn>
</div>



<div class="left">

</div>
<div class="clearfix"></div>
