<?php
/**
 * This file is part of Project Chaplin.
 *
 * Project Chaplin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Project Chaplin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Project Chaplin. If not, see <http://www.gnu.org/licenses/>.
 *
 * @package    Project Chaplin
 * @author     Dan Dart
 * @copyright  2012-2013 Project Chaplin
 * @license    http://www.gnu.org/licenses/agpl-3.0.html GNU AGPL 3.0
 * @version    git
 * @link       https://github.com/danwdart/projectchaplin
**/
?>
<h1>
    Latest Videos
</h1>
<div class="row text-center">
    <?php foreach($this->ittFeaturedVideos as $modelVideo):?>
    <a href="/video/watch/id/<?php echo $modelVideo->getVideoId();?>">
    	<div class="thumb col-lg-4 col-md-4 col-sm-6 col-xs-12">
    		<img src="<?php echo htmlentities($modelVideo->getThumbnail()).'?'.time();?>" alt="View Video"/>
    		<p><?php echo $modelVideo->getShortTitle();?></p>
    	</div>
    </a>
    <?php endforeach;?>
</div>
<?php if (!$this->ittNodes->isEmpty()) : ?>
<div class="clearfix"></div>
<h1>
    Videos from other nodes
</div>
<div class="row text-center">
<?php foreach($this->ittNodes as $modelNode) :
foreach($modelNode->getFeaturedVideos() as $modelVideo):?>
<a href="/video/watchremote/node/<?php echo $modelNode->getNodeId()?>/id/<?php echo $modelVideo->getVideoId();?>">
	<div class="thumb col-lg-4 col-md-4 col-sm-6 col-xs-12">
		<img src="<?php echo htmlentities($modelVideo->getThumbnail()).'?'.time();?>" alt="View Video"/>
		<p><?php echo $modelVideo->getShortTitle();?></p>
	</div>
</a>
<?php endforeach; endforeach;?>
</div>
<?php endif; ?>
