<h1><?php echo $this->video->getTitle();?></h1>
<p>
    <video id="video" controls src="<?php echo $this->video->getFilename();?>">
    </video>
    
</p>
<h3>Actions:</h3>
<a href="/video/download/id/<?php echo $this->video->getVideoId();?>">Download</a>
<?php
	if ($this->video->isMine()):
?>
<a href="/video/delete/id/<?php echo $this->video->getVideoId();?>">Delete this video</a>
<?php endif;?>
<p><h3>
	<a class="ajax" href="/video/vote/id/<?php echo $this->video->getVideoId();?>/vote/up">Vote Up</a> | 
	<a class="ajax" href="/video/vote/id/<?php echo $this->video->getVideoId();?>/vote/down">Vote Down</a>
</h3></p>
<h2>Comments:</h2>
<?php if(Chaplin_Auth::getInstance()->hasIdentity()): echo $this->formComment; else: 
echo 'Login above to comment.'; endif;  ?>
<dl>
    <?php foreach($this->video->getComments() as $modelComment):?>
    <dt><?php echo $modelComment->getUsername();?></dt>
    <dd><?php echo $modelComment->getComment();?></dd>
    <?php endforeach; ?>
</dl>
<script>
(function() {

var elem = document.getElementById("video");

changefullscreen = function() {
    if(document.mozFullScreen || document.webkitIsFullScreen) {
    console.log('go nfs');
        if (elem.cancelFullScreen) {
          elem.cancelFullScreen();
        } else if (elem.mozCancelFullScreen) {
          elem.mozCancelFullScreen();
        } else if (elem.webkitCancelFullScreen) {
          elem.webkitCancelFullScreen();
        }
        
    } else {
    console.log('go fs');
        if (elem.requestFullScreen) {
        elem.requestFullScreen();
        } else if (elem.mozRequestFullScreen) {
          elem.mozRequestFullScreen();
        } else if (elem.webkitRequestFullScreen) {
          elem.webkitRequestFullScreen();
        }
    }
};

changefullscreenauto = function() {
    if(document.mozFullScreen || document.webkitIsFullScreen) {
        elem.oldwidth = elem.style.width;
        elem.oldheight = elem.style.height;
        elem.style.maxWidth = '100%';
        elem.style.maxHeight = '100%';
        elem.style.height = '100%';
        elem.style.width = '100%';
    } else {
        elem.style.maxWidth = '640px';
        elem.style.maxHeight = '480px';
        elem.style.height = elem.oldheight;
        elem.style.width = elem.oldwidth;
    }
};

elem.addEventListener('dblclick', changefullscreen);
elem.addEventListener('mozfullscreenchange', changefullscreenauto);
elem.addEventListener('webkitfullscreenchange', changefullscreenauto);
elem.addEventListener('fullscreenchange', changefullscreenauto);

elem.addEventListener('click', function() {
    if(this.paused) {
        this.play();
    } else {
        this.pause();
    }
});

})();
</script>   
