<?php
/**
 * This file is part of Project Chaplin.
 *
 * Project Chaplin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Project Chaplin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Project Chaplin. If not, see <http://www.gnu.org/licenses/>.
 *
 * @package    Project Chaplin
 * @author     Dan Dart
 * @copyright  2012-2013 Project Chaplin
 * @license    http://www.gnu.org/licenses/agpl-3.0.html GNU AGPL 3.0
 * @version    git
 * @link       https://github.com/dandart/projectchaplin
**/
?>
<h1><?php echo $this->video->getTitle();?></h1>
<div id="videoarea">
	<video id="video" controls class="clicktoplay fullscreen"
		src="<?php echo $this->video->getFilename().'?'.time();?>">
	</video>
	<span id="fun">
		<button id="slower">&laquo; Slow Motion</button>
		<button id="normalspeed">Normal Speed</button>
		<button id="faster">Fast Forward &raquo;</button>
		<select class="effect">
			<option class="filter" value="none">-- Select Effect --</option>
		    <option class="filter" value="blur">Blur</option>
		    <option class="filter" value="gray">Grey</option>
		    <option class="filter" value="sepia">Sepia</option>
		    <option class="filter" value="bright">Bright</option>
		    <option class="filter" value="highcontrast">Contrast</option>
		    <option class="filter" value="colour">Colourful</option>
		    <option class="filter" value="invert">Invert</option>
		    <option class="filter" value="saturate">Saturate</option>
		    <option class="filter" value="earthquake">Earthquake!</option>
		    <option class="filter" value="br">Barrel Roll!</option>
		    <option class="filter" value="drunk">Drunk!</option>
		</select>
	</span>
</div>
<div id="infoarea">
	<br/>
	<br/>Uploaded by: <a href="/user/<?php echo $this->video->getUsername(); ?>"><?php echo $this->video->getUsername(); ?></a>
	<br/>Uploaded on <?php echo date('d/m/Y H:i', $this->video->getTimeCreated());?> (<?php echo $this->video->getTimeAgo(); ?>)
	<br/>Licence: <a href="<?php echo $this->video->getLicence()->getURL(); ?>"><?php echo $this->video->getLicence()->getText(); ?></a>
	<br/><?php echo $this->video->getDescription(); ?>
	<p>Short URL: <input type="text" disabled value="<?php echo $this->short; ?>"/></p>
	<p><strong>&uparrow; <?php echo $this->video->getVotesUp(); ?> / <?php echo $this->video->getVotesDown(); ?> &downarrow;</strong></p>
	<p><?php echo $this->twittershare; ?></p>
	<br/>
	<?php if(Chaplin_Auth::getInstance()->hasIdentity()): 
	if ('1' === $this->video->getYourVote()) :
	echo '+1';
	else:?>
	<a class="atotext" href="/video/vote/id/<?php echo $this->video->getVideoId();?>/vote/up">+1</a>
	<?php endif; echo ' / ';
	if ('0' === $this->video->getYourVote()) :
	echo '-1';
	else:?>
	<a class="atotext" href="/video/vote/id/<?php echo $this->video->getVideoId();?>/vote/down">-1</a>
	<?php endif;?>&nbsp;&nbsp;
	<?php endif; ?>
	<a href="/video/download/id/<?php echo $this->video->getVideoId();?>">Download</a>
	<?php
		if ($this->video->isMine()):
	?>
	    | <a href="/video/delete/id/<?php echo $this->video->getVideoId();?>">Delete</a> | 
	    <a href="/video/edit/id/<?php echo $this->video->getVideoId();?>">Edit</a>
	<?php endif;?>
	<br/>
	<?php if(Chaplin_Auth::getInstance()->hasIdentity()): echo $this->formComment; else: 
	echo 'Login above to comment.'; endif;  ?>
	<br/>
	<div id="comments" rel="/video/comments/id/<?php echo $this->video->getVideoId();?>">
		<?php foreach($this->ittComments as $modelComment):?>
		<p>
			<i>
				<?php echo $modelComment->getUsername();?>
			</i> said: 
			<?php echo $modelComment->getComment();?>
			<?php if ($modelComment->isMine()): ?>
				<a class="ajax" href="/video/deletecomment/id/<?php echo $modelComment->getCommentId(); ?>" 
					rel="comments">
				(X)
				</a>
			<?php endif;?>
		</p>
	<?php endforeach; ?>
	</div>
</div>
<script src="/js/k.js"></script>
<script src="/js/video.js"></script>