<?php
/**
 * This file is part of Project Chaplin.
 *
 * Project Chaplin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Project Chaplin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Project Chaplin. If not, see <http://www.gnu.org/licenses/>.
 *
 * @package    Project Chaplin
 * @author     Dan Dart
 * @copyright  2012-2013 Project Chaplin
 * @license    http://www.gnu.org/licenses/agpl-3.0.html GNU AGPL 3.0
 * @version    git
 * @link       https://github.com/dandart/projectchaplin
**/
?>
<h1><?php echo $this->entryVideo->getVideoTitle();?></h1>
<div id="videoarea">
	<iframe 
		class="youtube-player"
		type="text/html"
		width="640"
		height="385"
		src="<?php echo $this->strScheme; ?>://www.youtube.com/embed/<?php echo $this->entryVideo->getVideoId(); ?>"
		frameborder="0"
	>
	</iframe>
</div>
<div id="infoarea">
	<h3>Uploaded on <?php echo date('d/m/Y H:i', strtotime($this->entryVideo->getPublished()));
		$author = $this->entryVideo->getAuthor()[0];
		$strUserUri = $author->getUri()->getText();
		$strUsername = substr(strrchr($strUserUri, '/'),1);
		$strName = $author->getName();
	?> by <a href="/user/youtube/id/<?php echo $strUsername; ?>"><?php echo $strName; ?></a>
	</h3>
	<br/>
	<span style="font-size:8pt;"><?php echo str_replace("\n", '<br/>', $this->entryVideo->getVideoDescription()); ?></span>
	<br/>
	<a class="btn btn-success" href="/video/importyoutube/id/<?php echo $this->entryVideo->getVideoId();?>"><i class="fa fa-download"></i> Import</a>
	<?php if ($this->isLocal) : ?>
	<a class="btn btn-primary" href="<?php echo $this->videoURL;?>"><i class="fa fa-download"></i> Download</a>
	<?php endif; ?>
	<br/>
	<?php if(Chaplin_Auth::getInstance()->hasIdentity()): echo $this->formComment; else: 
	echo 'Login above to comment.'; endif;  ?>
</div>
<script src="/js/video.js"></script>
