<?php
/**
 * This file is part of Project Chaplin.
 *
 * Project Chaplin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Project Chaplin is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Project Chaplin. If not, see <http://www.gnu.org/licenses/>.
 *
 * @package    Project Chaplin
 * @author     Dan Dart
 * @copyright  2012-2013 Project Chaplin
 * @license    http://www.gnu.org/licenses/agpl-3.0.html GNU AGPL 3.0
 * @version    git
 * @link       https://github.com/dandart/projectchaplin
**/
?>
<h1><?php echo $this->entryVideo->getVideoTitle();?></h1>
<?php if ($this->isLocal) : ?>
	<video id="video" class="clicktoplay fullscreen" controls src="<?php echo $this->videoURL;?>">
	</video>
<?php else : ?>
	<iframe class="youtube-player" type="text/html" width="640" height="385" src="http://www.youtube.com/embed/<?php echo $this->entryVideo->getVideoId(); ?>" frameborder="0">
	</iframe>
<?php endif; ?>
<h3>Uploaded: <?php echo date('d/m/Y H:i', strtotime($this->entryVideo->getPublished())); ?></h3>
<br/><i>To watch on all devices, import this video to Chaplin below.</i>
<br/>
<br/>
<span style="font-size:8pt;"><?php echo str_replace("\n", '<br/>', $this->entryVideo->getVideoDescription()); ?></span>
<br/>
<a href="/video/importyoutube/id/<?php echo $this->entryVideo->getVideoId();?>">Import</a> |
<a class="ajax" href="/video/vote/id/<?php echo $this->entryVideo->getVideoId();?>/vote/up">+1</a> /
<a class="ajax" href="/video/vote/id/<?php echo $this->entryVideo->getVideoId();?>/vote/down">-1</a> &nbsp;&nbsp;
<a href="/video/download/id/<?php echo $this->entryVideo->getVideoId();?>">Download</a>
<br/>
<?php if(Chaplin_Auth::getInstance()->hasIdentity()): echo $this->formComment; else: 
echo 'Login above to comment.'; endif;  ?>
<br/>
<script src="/js/video.js"></script>
