<a href="javascript:;" onclick="window.open(\'https://sharetodiaspora.github.io/?url=\'+encodeURIComponent(location.href)+\'&title=\'+encodeURIComponent(document.title),\'das\',\'location=no,links=no,scrollbars=no,toolbar=no,width=620,height=550\'); return false;" rel="nofollow" target="_blank">
    <img src="https://sharetodiaspora.github.io/favicon.png" style="border: 0px solid;" />
    Share on Diaspora
</a>
