<h2>Import Files</h2>
<p>Since you own this instance, you can import your media collection to Project Chaplin.</p>
<p>Please specify the location of the files you wish to import.</p>
<br/>
<?php echo $this->form; ?>
<br/><br/><br/><br/>
<style>
form.fileimport div {
	padding: 2px 2px 2px 15px;
	float:left;
	position: relative;
	width: 200px;
	height: 10px;
	margin: 4px;
	overflow: hidden;
	font-size: 8pt;
}

form.fileimport div label {
	width: 100%;
	height: 100%;
}

form.fileimport div input[type="checkbox"] {
	position: absolute;
	top:5px;
	left: 0;
}
</style>